version: "3.8"
services:
  app:
    container_name: juleb-test-server
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
    networks:
      - web
      - service1
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env
    networks: 
      - service1
networks:
  service1:
  web:
volumes:
  postgres:
    driver: local