version: "3.8"
services:
  app:
    image: ${DOCKER_HUB_USERNAME}/${APP_NAME}:${APP_VER}
    container_name: ${APP_NAME}
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    env_file:
      - .env
volumes:
  postgres:
    driver: local