version: "3"
services:
  app:
    container_name: juleb-test-server
    restart: always
    build: .
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    links:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    env_file:
      - .env
volumes:
  postgres:
    driver: local